version: '3'

services:
  ksbd-keycloak:
    image: quay.io/keycloak/keycloak:12.0.1
    container_name: ksbd-keycloak
    networks:
      - net
    ports:
      - 7070:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    restart: unless-stopped

networks:
  net:
    driver: bridge
